<?php
require "vendor/autoload.php";
require "controllers/MailController.php";

use PHPUnit\Framework\TestCase;

class MailControllerTest extends TestCase
{


    private $mailController;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mailController = new MailController();
    }

    public function test_champsVide()
    {

        $actual = $this->mailController->checkChamps("");

        $this->assertEquals("Champs vide", $actual);
    }
    public function test_arobasenonpresent()
    {

    $actual = $this->mailController->checkChamps("zelda");

    $this->assertEquals("@ non présent", $actual);

    }

}
